# Workflow para construir e fazer deploy de um projeto Angular no GitHub Pages
name: Deploy Angular App to GitHub Pages

on:
  push:
    branches: [ "master" ] # Executa o workflow em cada push na branch master
  workflow_dispatch: # Permite iniciar o workflow manualmente pela aba Actions

# Configura as permissões necessárias
permissions:
  contents: read
  pages: write
  id-token: write

# Define a política de concorrência para o deploy
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar pnpm
        run: npm install -g pnpm

      - name: Instalar dependências
        run: pnpm install

      - name: Construir o projeto
        run: pnpm run build --configuration production # Constrói o projeto Angular para produção

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist/voronoi-delaunay # Caminho dos arquivos de build

  # Job de deploy
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy para GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
